config/routes.rb
Rails.application.routes.draw do
  resources :rsses

end

app/models/concerns/loggable.rb
module Loggable
  def logx(message)
    puts(":xxx: #{Time.now.to_s} :: #{message}") if Rails.env.development?
  end
end

app/models/rss.rb
class Rss < ActiveRecord::Base
  extend Loggable

  delegate :feed, to: :rss_klass

  FEEDS = [
      {
          name: "Reddit Psychology",
          description: "psychology",
          uid: "psychology",
          url: "https://www.reddit.com/r/psychology.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Reddit Productivity",
          description: "productivity",
          uid: "productivity",
          url: "https://www.reddit.com/r/productivity.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Reddit Business",
          description: "business",
          uid: "business",
          url: "https://www.reddit.com/r/business.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Reddit Economics",
          description: "economics",
          uid: "economics",
          url: "https://www.reddit.com/r/Economics.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Rails",
          description: "rails",
          uid: "rails",
          url: "https://www.reddit.com/r/rails.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Ruby on Rails",
          description: "ruby on rails",
          uid: "rubyonrails",
          url: "https://www.reddit.com/r/rubyonrails.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Agile",
          description: "agile",
          uid: "agile",
          url: "https://www.reddit.com/r/agile.rss",
          rss_type: "SubredditRss"
      },
      {
          name: "Programming",
          description: "programming",
          uid: "programming",
          url: "https://www.reddit.com/r/programming.rss",
          rss_type: "SubredditRss"
      }
  ]

  def self.seed
    logx "Creating feeds.."
    
    FEEDS.each do |feed|
      Rss.find_or_create_by!(uid: feed[:uid]) do |rss|
        rss.name        = feed[:name]
        rss.url         = feed[:url]
        rss.description = feed[:description]
        rss.rss_type    = feed[:rss_type]
      end
    end
  end

  private

  def rss_klass
    @rss_klass ||= rss_type.constantize.new(url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsses_controller.rb
class RssesController < ApplicationController
  before_action :set_rss, only: :show

  def index
    @rsses = Rss.all
  end

  def show
    @posts = Rails.cache.read("feed-#{params[:id]}")
  end

  private
    def set_rss
      @rss = Rss.find_by(uid: params[:id])
    end

    def rss_params
      params.require(:rss).permit(:name, :uid, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rsses_helper.rb
module RssesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssRewrite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsses/_form.html.erb
<%= form_for(@rss) do |f| %>
  <% if @rss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss.errors.count, "error") %> prohibited this rss from being saved:</h2>

      <ul>
      <% @rss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsses/edit.html.erb
<h1>Editing Rss</h1>

<%= render 'form' %>

<%= link_to 'Show', @rss %> |
<%= link_to 'Back', rsses_path %>

app/views/rsses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rsses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Uid</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsses.each do |rss| %>
      <tr>
        <td><%= rss.name %></td>
        <td><%= rss.uid %></td>
        <td><%= rss.url %></td>
        <td><%= link_to 'Show', rss %></td>
        <td><%= link_to 'Edit', edit_rss_path(rss) %></td>
        <td><%= link_to 'Destroy', rss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rss', new_rss_path %>

app/views/rsses/new.html.erb
<h1>New Rss</h1>

<%= render 'form' %>

<%= link_to 'Back', rsses_path %>

app/views/rsses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rss.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @rss.uid %>
</p>

<p>
  <strong>Url:</strong>
  <%= @rss.url %>
</p>

<%= link_to 'Edit', edit_rss_path(@rss) %> |
<%= link_to 'Back', rsses_path %>